[package]
name = "klavier-player"
version = "0.1.2"
edition = "2024"
description = "MIDI player library of klavier."
license = "Apache-2.0"
documentation = "https://github.com/ruimo/klavier-player"
homepage = "https://github.com/ruimo/klavier-player"
repository = "https://github.com/ruimo/klavier-player"

[dependencies]
klavier-helper = "0.1.11"
#klavier-helper = { path = "../klavier-helper" }
klavier-core = "0.1.15"
#klavier-core = { path = "../klavier-core" }
error-stack = "^0"
once_cell = "^1"
tracing = "^0"
midir = "^0"
spin_sleep = "1.3.3"
thread-priority = "3"
